### ISSUE TITLE
WebAuthRequired

### ISSUE THREAD

**Issue by kasperkronborg** [SargoDarya/bungie-platform#2]
I have provided the cookie values for my bungledid, bungled and bungleatk as mentioned in the README, but still I keep getting errorStatus: WebAuthRequired with errorMessage: Please sign-in to continue.

Bungie platform is being initialised like this: var platform = BungiePlatform("bungledid={my-bungledid};bungled={my-bungled};bungleatk={my-bungleatk}");

Any thoughts?

**Comment by mooshee** [comment]
Any updates on this?  I too continue to get the WebAuthRequired error, despite providing my cookie string.

**Comment by ToothpickFactory** [comment]
Same here. Any updates?

**Comment by TheHandsomeCoder** [comment]
Looking through the code I think the Cookie needs to be passed as a string, though I still get the Webauth error even when this is passed

**Comment by Rikkert2x** [comment]
the cookies should be parsed in the headers of a request as:
Set-Cookie: *********

**Comment by ToothpickFactory** [comment]
Would you mind putting in a full example?

**Comment by Rikkert2x** [comment]
I would love to do that but ive build a php scrio and use this as a reference for the end points

**Comment by ToothpickFactory** [comment]
Gotcha. I would love to see that PHP script if you are willing to share it.

**Comment by Rikkert2x** [comment]
ill zip my project this weekend on my pc.
The project is currently in the beginng stage.
ive started to document the api end points but its a pain in the ass because of the lack of proper documentation.

**Comment by ToothpickFactory** [comment]
I know what you mean. I would like to create a good node version but I know PHP if you would like help on it.

**Comment by Rikkert2x** [comment]
@ToothpickFactory
You can find the download right here:
http://www.rickdeman.nl/ToothPickFactory.zip

If you are also planning to build a node like me, maybe we could help eachother out?

**Comment by ToothpickFactory** [comment]
Agreed. My direct email is austin.d.lovell@gmail.com.  let's talk over
email.

**Comment by benbabics** [comment]
Where in the world do I obtain the `bungledid`, `bungled` and `bungleatk`? I'm brand new to the Bungie API, so please excuse me. I received an API Key from the [Bungie API Website](https://www.bungie.net/en/User/API), but it appears I am in need of these other params. Any help is much appreciated.

**Comment by benbabics** [comment]
Oh... looking into this further it appears those are in the cookie set after authing.
