### ISSUE TITLE
The api website doesn't work

### ISSUE THREAD

**Issue by ibbatta** [SargoDarya/bungie-platform#5]
Hi,

I am trying to reach `http://bungie-platform.herokuapp.com/` but the website seems down

**Comment by SargoDarya** [comment]
Hey Ibbatta, sorry for the long wait. The website is hosted on a free dyno on heroku so it starts to sleep at some point. Try again at a later time or try running it yourself.

**Comment by ibbatta** [comment]
@SargoDarya sorry mate, i didn't know. Thanks for explanation (I am curious to try asap)
